version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - yarn
      - run: ls -alFG
