version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      # - run: yarn
      - run: git clone git@github.com:sinpaout/Bwild.git -b develop && cd Bwild && ls -alFG
      # - run:
      #     name: Move to build
      #     command: |
      #       rm -rf Bwild
      #       ls -alFG
      #       git clone git@github.com:sinpaout/Bwild.git -b develop
      #       cd Bwild
      #       ls -alFG
      - run:
          name: Commit builded content
          command: |
            git config --global user.email "minthit21dj@gmail.com"
            git config --global user.name "Thet Win Aung"
            echo "<h2>Hello world</h2>" > docs/index.html
            date "+%F %T" >> docs/index.html
            # git commit -a --amend --no-edit
            # git push -f origin HEAD
